#### What is NumPy?

  NumPy is the fundamental package for scientific computing in Python. It is a Python library that provides a multidimensional array object, various derived objects (such as masked array and matrices).

  At the core of the NumPy package, is the N-D array object. This encapsulates n-dimensional arrays of homogeneous data types.

#### NumPy v/s Python Sequences

1.) NumPy array have a fixed size at creation, unlike Python lists (which can grow dynamically). Changing the size of an nd-array will create a new array and delete the original.

2.) The elements in a NumPy array are all required to be of the same data type, and thus will be the same size in memory.

3.) NumPy arrays facilitate advanced mathematical and other types of operations on large numers of data.

4.) Various other libraries like Pandas, SciKit, MatplotLib etc. used core concept of NumPy array oject.

### Creating NumPy Arrays

Following functions are used to create different types of arrays.

1. np.array and np.dtype
2. np.arange and np.reshape
3. np.ones, np.zeros and np.random
4. np.linspace
5. np.identity


In [3]:
# np.array: need to import numpy as np short form

import numpy as np

a = np.array([1,2,3])   #like list in python. We can called it as vector or one dimensional array
print(a)
print(type(a))

[1 2 3]
<class 'numpy.ndarray'>


In [5]:
# 2D: can create 2D array called as matrix
b = np.array([[1,2,3],[4,5,6]])  #can called it as matrix
print(b)

[[1 2 3]
 [4 5 6]]


In [6]:
# 3D array: used to create 3D array called tensors

c = np.array([[[1,2,3],[4,5,6]],[[4,3,1],[9,6,5]]])
print(c)   #can call it as tensor


[[[1 2 3]
  [4 5 6]]

 [[4 3 1]
  [9 6 5]]]


In [10]:
# dtype: can create NumPy array of own choice using dtype.

d = np.array([2,3,4],dtype=float)
print(d)

e = np.array([0,1,4,0], dtype=bool)
print(e)  #consider 0 as false and treat other any non zero number as 1

f = np.array([5,3,6,9],dtype = complex)
print(f)

[2. 3. 4.]
[False  True  True False]
[5.+0.j 3.+0.j 6.+0.j 9.+0.j]


In [12]:
# arange function: to find the range of given parameters

g = np.arange(1,11,2)
print(g)

[1 3 5 7 9]


In [16]:
# reshape: convert the shape of array. But condition is that the product of two numbers equal to the given range of array.

h = np.arange(1,13).reshape(3,4)  #can change the order to 4*3
print(h)

h1 = np.arange(1,13).reshape(6,2)  #can change the order to 2*6
print(h1)

h2 = np.arange(1,13).reshape(5,4)  #can change the order to 4*3
print(h2)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]
 [11 12]]


ValueError: cannot reshape array of size 12 into shape (5,4)

In [18]:
# np.ones and np.zeros: can create numpy array whose all elements are one or zero at the same time
# need to provide tuple (3,4) here
# used where you need to initialize something immediately

i = np.ones((3,4))
print(i)

i1 = np.zeros((3,4))
print(i1)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [23]:
# np.random: generates random numbers between the given range.

j = np.random.random((1,9))
print(j)

[[0.19302721 0.94690521 0.00774238 0.99345557 0.2891663  0.01267164
  0.32661505 0.23650489 0.74014843]]


In [25]:
# np.linspace: generate linear items in the given range with equal distances

k = np.linspace(-10,10,10)
print(k)

# where -10 defines the lower range; 10 defines the upper range and 10 defines the number of items to generate

[-10.          -7.77777778  -5.55555556  -3.33333333  -1.11111111
   1.11111111   3.33333333   5.55555556   7.77777778  10.        ]


In [26]:
# np.identity: used to create identity matrix(whose diagonal items are 1)

l = np.identity(3)
print(l)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
