#### What is NumPy?

  NumPy is the fundamental package for scientific computing in Python. It is a Python library that provides a multidimensional array object, various derived objects (such as masked array and matrices).

  At the core of the NumPy package, is the N-D array object. This encapsulates n-dimensional arrays of homogeneous data types.

#### NumPy v/s Python Sequences

1.) NumPy array have a fixed size at creation, unlike Python lists (which can grow dynamically). Changing the size of an nd-array will create a new array and delete the original.

2.) The elements in a NumPy array are all required to be of the same data type, and thus will be the same size in memory.

3.) NumPy arrays facilitate advanced mathematical and other types of operations on large numers of data.

4.) Various other libraries like Pandas, SciKit, MatplotLib etc. used core concept of NumPy array oject.

### Creating NumPy Arrays

Following functions are used to create different types of arrays.

1. np.array and np.dtype
2. np.arange and np.reshape
3. np.ones, np.zeros and np.random
4. np.linspace
5. np.identity


### In simple terms Numpy

##### Numpy is a scientific computing library, jisme ek important cheez hoti hai wo hai numpy array aur us array se kuch aur objects bhi bnaye gye hain numpy library k ander jaise ki metrices, masked array, structured array; ye kuch derrived objects hain aur numpy in objects k uper kuch functionality provide krta hai jo aap apply kr skte ho jaise mathematical functions, i/o,sorting, searching, linear algebra, statistics functions etc.

###### All in all ek mathematical library hai and jo sbse main cheez hai wo hai array object jaise python ka data type hota hai list usi tarike se numpy ka datatype hai jisko hm bulate hain numpy array (core of numpy). Numpy array homogenous data types ko hold karta hai, means usme hm ek hi type ka data rakh skte hain.

##### What is the need of Numpy? (jrurat kyn hai numpy ki?)
###### pehle jb data science ya analysis kiya jata tha tho wo matlab ya R language me hota tha kynki uss time pe python ko slow programming language consider kiya jata tha. kynki python ke datatypes design ki wajah se slow hain. fir jb Numpy existence me aya jisme numpy array object ka use hota tha, usme Numpy array ko bnaya gya C mein but syntax rakha gya python ka kynki python ka syntax easy hai, to iss se hme comfortable mila python ka and speed mili C wali aur data science and analysis krna easy ho gya. pandas, matplotlib, scikit learn sbhi numpy object based libraries hain.

In [32]:
# np.array: import numpy as np (short form)

import numpy as np

a = np.array([1,2,3])   #like list in python. We can called it as vector or one dimensional array
print(a)
print(type(a))

[1 2 3]
<class 'numpy.ndarray'>


In [33]:
# 2D: can create 2D array called as matrix
b = np.array([[1,2,3],[4,5,6]])  #can called it as matrix
print(b)

[[1 2 3]
 [4 5 6]]


In [34]:
# 3D array: used to create 3D array called tensors

c = np.array([[[1,2,3],[4,5,6]],[[4,3,1],[9,6,5]]])
print(c)   #can call it as tensor


[[[1 2 3]
  [4 5 6]]

 [[4 3 1]
  [9 6 5]]]


In [35]:
# dtype: can create NumPy array of own choice using dtype.

d = np.array([2,3,4],dtype=float)
print(d)

e = np.array([0,1,4,0], dtype=bool)
print(e)  #consider 0 as false and treat other any non zero number as 1

f = np.array([5,3,6,9],dtype = complex)
print(f)

[2. 3. 4.]
[False  True  True False]
[5.+0.j 3.+0.j 6.+0.j 9.+0.j]


In [36]:
# arange function: to find the range of given parameters

g = np.arange(1,11,2)
print(g)

[1 3 5 7 9]


In [37]:
# reshape: convert the shape of array. But condition is that the product of two numbers equal to the given range of array.

h = np.arange(1,13).reshape(3,4)  #can change the order to 4*3
print(h)

h1 = np.arange(1,13).reshape(6,2)  #can change the order to 2*6
print(h1)

h2 = np.arange(1,13).reshape(5,4)  #can't do this because the range is 12 and product is 20,which is not possible
print(h2)  #produce value error

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]
 [11 12]]


ValueError: cannot reshape array of size 12 into shape (5,4)

In [69]:
# np.ones and np.zeros: can create numpy array whose all elements are one or zero at the same time
# need to provide tuple (3,4) here
# use case: where you need to initialize something immediately

i = np.ones((3,4))
print(i)

i1 = np.zeros((3,4))
print(i1)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [71]:
# np.random: generates random numbers between the given range.

j = np.random.random((1,9))
print(j)

[[0.22125448 0.36354413 0.11949553 0.87603803 0.82982665 0.79044193
  0.26993978 0.10585935 0.86385896]]


In [73]:
# np.linspace: generate linear items in the given range with equal distances

k = np.linspace(-10,10,10)
print(k)

# where -10 defines the lower range; 10 defines the upper range and 10 defines the number of items to generate

[-10.          -7.77777778  -5.55555556  -3.33333333  -1.11111111
   1.11111111   3.33333333   5.55555556   7.77777778  10.        ]


In [75]:
# np.identity: used to create identity matrix(whose diagonal items are 1)

l = np.identity(3)
print(l)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


### Numpy Array Attributes
##### Har numpy array numpy class ka object hai to har numpy array jo hm bna rhe hain wo numpy class ke kuch attributes ko access kar sakta hai, here we are going to discuss those numpy class ke attributes.

In [78]:
a1 = np.arange(10)    #vector
a2 = np.arange(12, dtype=float).reshape(3,4)    #matrix or 2D array
a3 = np.arange(8).reshape(2,2,2)      #tensor or multidimensional array

print("\n",a1)
print("\n",a2)
print('\n',a3)


 [0 1 2 3 4 5 6 7 8 9]

 [[ 0.  1.  2.  3.]
 [ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]]

 [[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]


In [80]:
# ndim (number of dimension): given array ka dimension btata hai ki array 1D,2D,3D ya multidimensional hai

print(a1.ndim)
print(a2.ndim)
print(a3.ndim)

1
2
3


In [82]:
# shape: tells ki har dimension mein kitne items hain, example matrix me rows and columns kitne hain

print(a1.shape)
print(a2.shape)
print(a3.shape)    # results (2,2,2) which means (no.of arrays, no.of rows, no. of columns)

(10,)
(3, 4)
(2, 2, 2)


In [84]:
# size: tells the number of items in array

print(a1.size)
print(a2.size)
print(a3.size)

10
12
8


In [86]:
# itemsize: tells har item memory mein kitna size occupy kar rha hai

print(a1.itemsize)
print(a2.itemsize)
print(a3.itemsize)

4
8
4


In [88]:
# dtype: tells the datatype of items in an array

print(a1.dtype)
print(a2.dtype)
print(a3.dtype)

int32
float64
int32


### Changing Datatype

In [91]:
# astype: to represent a higher data type to lower data type (example int64 to int32, float to int32)
# astype is basically to reduce the memory size of a column where it is reqd. to reduce.

a3.astype(np.int32)

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

### Array Operations:
###### we can perform all mathematical operations on array. Two type of operations we have Scalar and Vector.

In [94]:
a1 = np.arange(12).reshape(3,4)
a2 = np.arange(12,24).reshape(3,4)

print(a1)
print(a2)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]


In [96]:
# Scalar operation: We can perform all aritmetic operations.
# #(Scalar operation numpy array and scalar (yani number) ke beech me hota hai).
# arithmetic

print(a1 * 3)    # multiplies each item of matrix a1 with scalar 3.

[[ 0  3  6  9]
 [12 15 18 21]
 [24 27 30 33]]


In [98]:
# relational: Can perform all relational operations

print(a2 > 15)    # make comparison of each element of matrix with the provided scalar

[[False False False False]
 [ True  True  True  True]
 [ True  True  True  True]]


In [100]:
# Vector operations: When we apply an operator on two numpy arrays. We can perform all operations here in numpy array matrix.
#(vector operation 2 numpy arrays ke beech me hota hai). But shape should be same in this case.
print(a1+a2)
print(a1*a2)
print(a1/a2)
print(a1|a2)

[[12 14 16 18]
 [20 22 24 26]
 [28 30 32 34]]
[[  0  13  28  45]
 [ 64  85 108 133]
 [160 189 220 253]]
[[0.         0.07692308 0.14285714 0.2       ]
 [0.25       0.29411765 0.33333333 0.36842105]
 [0.4        0.42857143 0.45454545 0.47826087]]
[[12 13 14 15]
 [20 21 22 23]
 [28 29 30 31]]


### Numpy Array Functions

In [103]:
# randomly generated array

a1 = np.random.random((3,3))   #generate random number between 1 to 100
a1 = np.round(a1*100)    #to round of the items multiply array a1 with 100
print(a1)

[[78.  6.  0.]
 [98. 61.  5.]
 [ 1. 74. 29.]]


In [105]:
# min/max/sum/prod: provide minimum, maximum, sum, product of array items.

print(np.min(a1))
print(np.max(a1))
print(np.sum(a1))
print(np.prod(a1))

0.0
98.0
352.0
0.0


In [107]:
# if you want to find the har row ka min, max, sum, product.
# 0 means column and 1 means row for axis value

print(np.min(a1,axis=0))   # column wise
print(np.max(a1,axis=1))   # row wise
print(np.sum(a1,axis=0))  
print(np.prod(a1,axis=1)) 

[1. 6. 0.]
[78. 98. 74.]
[177. 141.  34.]
[    0. 29890.  2146.]


In [109]:
# mean/median/std/var: can calculate statistical operations

print(np.mean(a1,axis=0))   # display mean of column items
print(np.median(a1,axis=1))   # display median of row items
print(np.var(a1,axis=0))    # display variance of column items
print(np.std(a1,axis=1))    # diplay standard deviation of row items

[59.         47.         11.33333333]
[ 6. 61. 29.]
[1748.66666667  868.66666667  160.22222222]
[35.44009029 38.2302963  30.07028803]


In [111]:
# trigonometric functions: to calculate trigonometric functions

print(np.sin(a1))   # calculate sin of matrix items

[[ 0.51397846 -0.2794155   0.        ]
 [-0.57338187 -0.96611777 -0.95892427]
 [ 0.84147098 -0.98514626 -0.66363388]]


In [113]:
# dot product: Dot product works only when the no. of columns of one matrix and no. of rows of second matrix are same
# Example: dot product is applicable only if two matrices are in 3*4 and 4*3 form which results 3*3 matrix (means rows*rows) form.

a2 = np.arange(12).reshape(3,4)
a3 = np.arange(12,24).reshape(4,3)

print(np.dot(a2,a3))   # will result the dot product

[[114 120 126]
 [378 400 422]
 [642 680 718]]


In [115]:
# log and exponents

print(np.log(a1))
print(np.exp(a1))

[[4.35670883 1.79175947       -inf]
 [4.58496748 4.11087386 1.60943791]
 [0.         4.30406509 3.36729583]]
[[7.49841700e+33 4.03428793e+02 1.00000000e+00]
 [3.63797095e+42 3.10429794e+26 1.48413159e+02]
 [2.71828183e+00 1.37338298e+32 3.93133430e+12]]


C:\Users\Anand S\AppData\Local\Temp\ipykernel_17508\1426890169.py:3: RuntimeWarning: divide by zero encountered in log
  print(np.log(a1))


In [117]:
# round/floor/ceil
# round():- nearest integer pe round off karta hai
# floor:- peechey wale integer pe round off krta hai (example: 5.9 = 5, 8.4 = 8)
# cell:- aagey wale integer pe round of krta hai (example: 5.1 = 6, 7.6 = 8)
# result varies bcz we take random valueshere

print(np.random.random((2,3)) * 100)    # generates random float values
print(np.round(np.random.random((2,3)) * 100))   # but round() rounds off the float values to integer

print(np.floor(np.random.random((2,3)) * 100))  # peechey wale integer pe round off krta hai

print(np.ceil(np.random.random((2,3)) * 100))   # aagey wale integer pe round of krta hai

[[87.1352834  79.78715371 27.64229116]
 [36.63313184 91.69866845 22.86311268]]
[[14. 42. 15.]
 [45. 48. 93.]]
[[68. 97. 96.]
 [39. 49. 32.]]
[[54. 29. 11.]
 [28. 97.  1.]]


### Indexing and Slicing

    Indexing: To find single item from the matrix we use indexing.
    Slicing: To find multiple items from the matrix  we use slicing.

#### Note*: Kitne bhi dimension ka array ho indexing se hum koi bhi item aur slicing se kitni bhi multiple items nikal skte hain 

In [119]:
# Indexing: To find a single item at a time from matrix

a1 = np.arange(10)
a2 = np.arange(12).reshape(3,4)
a3 = np.arange(8).reshape(2,2,2)

print('\n',a1)
print('\n',a2)
print('\n',a3)


 [0 1 2 3 4 5 6 7 8 9]

 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

 [[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]


In [121]:
# Indexing in 1D array

#a1: to find any item in array we need to put the index number as we done in python. it is simple indexing

a1[-1]
a1[3:8]

array([3, 4, 5, 6, 7])

In [123]:
# Indexing in 2D array


#a2: to find the item in matrix we need to specify the row number and column number of that matrix
print(a2)

print(a2 [1,2] )  # to find 6 in matrix a2

# to find 11 in matrix a2
print(a2[2,3])

# to find 10
print(a2[2,2])

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
6
11
10


In [317]:
# Indexing in 3D array


# a3: to find the item in 3D matrix (tensor). to find item in 3D tensor we need to put the matrix number and inside matrix's row and column number as we done in 2D matrix

print(a3)

# to find 5
print(a3[1,0,1])

# to find 3
print(a3[0,1,1])

#to find 6
print(a3[1,1,0])

# to find 0 
print(a3[0,0,0])

[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]
5
3
6
0


In [127]:
# Slicing in 1D array

# Slicing: to find the multiple items at the same time

# a1: to find item in array
# to find (2,3,4)
print(a1[2:5])

print(a1[0:6:2])  # stepping

[2 3 4]
[0 2 4]


In [155]:
# Slicing in 2D array

# a2: to find multiple items from a 2D matrix using slicing
# syntax to find multiple items: [row,:column] or [row:,column]
# Note*: jb bhi koi particular row chahiye to uske liye sare column chahiye hote hain and jb bhi koi particular column chahiye to uske liye sare rows chahiye hote hain

print(a2)
# to find first row
print('\n',a2[0,:])

# to find 3rd column (2,6,10)
print('\n',a2[0:,2])

# to find 3rd row (8,9,10,11)
print('\n',a2[2,:])

# to find 4th column (3,7,11)
print('\n',a2[:,3])

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

 [0 1 2 3]

 [ 2  6 10]

 [ 8  9 10 11]

 [ 3  7 11]


In [315]:
# Slicing in 2D array


# interesting operations on selection from a matrix

print(a2)

# to find 5,6 and 9,10 from a2
print('\n',a2[1:,1:3])

# to find 2,3 and 6,7
print('\n',a2[0:2,2:])    # a2[rows:rows,columns:columns]

# to find 0,3 and 8,11 (all corner items)
print('\n',a2[::2,::3])   #OR below code works same
print('\n',a2[0:3:2,0:4:3])     # (pehla wala chlta hai rows ke liye and 2sra wala columns k liye)

# to find 1,3 and 9,11 items
print('\n',a2[0::2,1::2])

# to find 4,7 and 8,11
print('\n',a2[1:3,::3])

# to find 5,7 and 9,11
print('\n',a2[1:,1::2])

# to find 2,3 and 6,7
print('\n',a2[:2,2:])

# to find 4,7
print('\n',a2[1::2,:4:3])   #OR
print('\n',a2[1,::3])   #will give the same result

# to find 5,6,7
print('\n',a2[1:2,1::])



#print('\n',a2[1])=print('\n',a2[1,])=print('\n',a2[1,:])

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

 [[ 5  6]
 [ 9 10]]

 [[2 3]
 [6 7]]

 [[ 0  3]
 [ 8 11]]

 [[ 0  3]
 [ 8 11]]

 [[ 1  3]
 [ 9 11]]

 [[ 4  7]
 [ 8 11]]

 [[ 5  7]
 [ 9 11]]

 [[2 3]
 [6 7]]

 [[4 7]]

 [4 7]

 [[5 6 7]]


In [386]:
# Slicing in 3D array

a3 = np.arange(27).reshape(3,3,3)
print(a3)

# beech wala array/matrix ke liye
print('\n',a3[1])

# to find 1st and 3rd array
print('\n',a3[0:3:2])

# to find 1st wale ka 2nd row (3,4,5)
print('\n',a3[0,1])

# to find 2nd wale ka beech wala column (10,13,16)
print('\n',a3[1,:,1])

# to find 3rd wale se (22,23 and 25,26)
print('\n',a3[2,1:,1:])

# to find 1st wale se 0,2 and 3rd wale se 18,20
print('\n',a3[::2,0,::2])

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]

 [[ 9 10 11]
 [12 13 14]
 [15 16 17]]

 [[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]

 [3 4 5]

 [10 13 16]

 [[22 23]
 [25 26]]

 [[ 0  2]
 [18 20]]


### Iterating on Numpy Array

In [407]:
# iteration on 1D arraya

print(a1)

for i in a1:
    print(i)   # prints each item one by one

[0 1 2 3 4 5 6 7 8 9]
0
1
2
3
4
5
6
7
8
9


In [403]:
# iteration on 2D array

print(a2)

for i in a2:
    print('\n',i)  # prints each row of 2D matrix every time

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

 [0 1 2 3]

 [4 5 6 7]

 [ 8  9 10 11]


In [401]:
# iteration on 3D array

print(a3)

for i in a3:
    print('\n',i)    # prints 3D array/matrix each time

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]

 [[0 1 2]
 [3 4 5]
 [6 7 8]]

 [[ 9 10 11]
 [12 13 14]
 [15 16 17]]

 [[18 19 20]
 [21 22 23]
 [24 25 26]]


In [413]:
# In case if you want to iterate array/matrix items one by one we use np.nditer() which breaks down the any multidimensional array into 1D array and prints each item of that multidimensional array/matrix

print(a3)

for i in np.nditer(a3):
    print(i)

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]
0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26


### Reshaping
    Here we discuss three main functions of reshaping:
    1.) reshape()
    2.) transpose()
    3.) ravel()

In [425]:
# reshape

a = np.arange(18).reshape(3,6)   #(rows,columns)
print(a)

a = np.arange(18).reshape(9,2)
print(a)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]]
[[ 0  1]
 [ 2  3]
 [ 4  5]
 [ 6  7]
 [ 8  9]
 [10 11]
 [12 13]
 [14 15]
 [16 17]]


In [445]:
# transpose: transpose a matrix (row -> column and column -> row
# (both a2.T and np.transpose(a2) will work)
print(a2)

a2.T
#OR
np.transpose(a2)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [453]:
# ravel: convert any dimensional array to one dimensional array
print(a2)

print(np.ravel(a2))

print(a)
np.ravel(a)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[ 0  1  2  3  4  5  6  7  8  9 10 11]
[[ 0  1]
 [ 2  3]
 [ 4  5]
 [ 6  7]
 [ 8  9]
 [10 11]
 [12 13]
 [14 15]
 [16 17]]


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17])

### Note*: Koi bhi function array mein changes nhi krta blki nya array bnata hai. As shown in following code

In [460]:
# a remains in 9*2 form even after apply numpy function to it.

print(a)

[[ 0  1]
 [ 2  3]
 [ 4  5]
 [ 6  7]
 [ 8  9]
 [10 11]
 [12 13]
 [14 15]
 [16 17]]


### Stacking: means adding two or more than two arrays, we can do this horizontally or vertically

##### Use of stacking: jb bhi same data multiple sources se aa rha ho like database, api, web scrapping tab hum stacking ka use krte hain similar data ka analysis krne k liye (vertially and horizontally),it is upto the requirement of the project. 
#### Stacking is basically multiple data sources ko jodne ka tarika hai. But stacking ka ek hi requirement hai ki data ka shape same hona chahiye.

In [499]:
# stacking

a4 = np.arange(12).reshape(3,4)
a5 = np.arange(12).reshape(3,4)

print(a4,'\n\n',a5)


[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]] 

 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [501]:
# horizontal stacking: add any number of arrays horizontally

print(np.hstack((a4,a5)))
print('\n',np.hstack((a4,a5,a4,a5)))    #can add any number of arrays

[[ 0  1  2  3  0  1  2  3]
 [ 4  5  6  7  4  5  6  7]
 [ 8  9 10 11  8  9 10 11]]

 [[ 0  1  2  3  0  1  2  3  0  1  2  3  0  1  2  3]
 [ 4  5  6  7  4  5  6  7  4  5  6  7  4  5  6  7]
 [ 8  9 10 11  8  9 10 11  8  9 10 11  8  9 10 11]]


In [503]:
# vertical stacking: add any number of arrays vertically

print(np.vstack((a4,a5)))
print('\n',np.vstack((a5,a4,a5,a4,a5)))

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


### Splitting: It is just the opposite of stacking. We split an array into two arrays.
### Requirement of splitting: jb bhi hum ek data source se multiple cheezen bnate hain. Example: College students ka data branch wise split krna ho to.

In [522]:
# horizontal splitting: split an array into horzontal format

print(a4)

print('\n',np.hsplit(a4,2))  # will split in 2 or 4 equal parts

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

 [array([[0, 1],
       [4, 5],
       [8, 9]]), array([[ 2,  3],
       [ 6,  7],
       [10, 11]])]


In [519]:
# vertical splitting: split an array into vertical format

print(a4)
print('\n', np.vsplit(a4,3))   # will split in 3 equal parts.

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

 [array([[0, 1, 2, 3]]), array([[4, 5, 6, 7]]), array([[ 8,  9, 10, 11]])]
