#### np.sort()
    Return a sorted copy of array.

In [5]:
import numpy as np

In [17]:
a = np.random.randint(20,90,20)
print(a)

[72 35 84 22 37 66 85 55 31 86 43 50 58 54 89 74 44 38 69 72]


In [19]:
b = np.random.randint(10,50,24).reshape(6,4)
print(b)

[[49 40 35 46]
 [43 34 37 29]
 [15 33 44 14]
 [31 23 49 20]
 [43 21 18 15]
 [43 25 17 20]]


In [21]:
np.sort(a)


array([22, 31, 35, 37, 38, 43, 44, 50, 54, 55, 58, 66, 69, 72, 72, 74, 84,
       85, 86, 89])